markdown: rdiscount
pygments: true
permalink: /:title
auto: true
rdiscount:
  extensions: [smart]
gravatar: 123
url: http://localhost:4000
ga: UA-25231338-1
title: Title
subtitle: Subtitle
author: My Name
exclude:
- Scripts
